# SPDX-License-Identifier: Apache-2.0

name: next build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: build
    runs-on: macos-15
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-apple-darwin, aarch64-unknown-linux-musl, x86_64-pc-windows-gnu, x86_64-unknown-linux-musl

      - name: install dependencies to make cross-compilation
        run: |
         brew install filosottile/musl-cross/musl-cross
         brew install mingw-w64

      - name: build all targets
        run: make release

      - name: attach all artifacts
        run: make release

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: linux
          path: ./release/rmlm-linux-*

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: macOS
          path: ./release/rmlm-mac-*

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windows
          path: ./release/rmlm-win-*
